# Generated by Django 3.2.6 on 2021-08-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.CharField(max_length=15)),
                ('telephone', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
    ]
