# Generated by Django 3.2.6 on 2021-08-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginkb', '0002_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
    ]
