# Generated by Django 3.2.6 on 2021-08-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginkb', '0003_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('nom', 'prenom')},
        ),
    ]
